{% set version = "6.7.2.22" %}
{% set build = 2 %}
{% set mpi = "openmpi" %}  # force this ... for now?
{% set mpi_prefix = "mpi_" + mpi %}
{% set build_pin = mpi_prefix + '_*' %}

package:
  name: casacpp
  version: {{ version }}

source:
  fn: casa-{{ version }}.tar.gz
  url: https://open-bitbucket.nrao.edu/rest/api/latest/projects/CASA/repos/casa6/archive?at=refs%2Ftags%2F{{ version }}&format=tgz
  sha256: 5b7327bac47803a774cb3f5e81ca3496c433348f725fba6ba54dd9e6221c45d9
  patches:
    - versioning.patch
    - protobuf-detection.patch

build:
  number: {{ build }}
  skip: true  # [win]
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('casacpp', max_pin='x.x.x') }} {{ build_pin }}

requirements:
  build:
    - cmake <4
    - bison
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - ninja
    - pkg-config
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
  host:
    - {{ mpi }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - casacore 3.7.1 {{ mpi_prefix }}_*_3  # only build with needed "fftpack" files right now
    - cfitsio
    - fftw
    - gsl
    - libboost-devel
    - libgrpc
    - libprotobuf
    - libsakura
    - libxml2
    - libxslt
    - sqlite
  run:
    - {{ mpi }}
    - libabseil
    - libopenblas

test:
  commands:
    {% set modules = [
      "air_casawvr",
      "alma",
      "asdmstman",
      "atmosphere",
      "atnf",
      "bnmin1",
      "calanalysis",
      "casadbus",
      "casa_sakura",
      "casatools",
      "components",
      "flagging",
      "graphics",
      "imageanalysis",
      "miriad",
      "mstransform",
      "msvis",
      "nrao",
      "parallel",
      "protobuf_generated",
      "singledishfiller",
      "singledish",
      "spectrallines",
      "stdcasa",
      "synthesis",
    ] %}
    {% for mod in modules %}
    - test -f $PREFIX/lib/libcasacpp_{{ mod }}${SHLIB_EXT}  # [unix]
    - test -d $PREFIX/include/casacpp/{{ mod }}  # [unix]
    {% endfor %}
    - test -f $PREFIX/lib/pkgconfig/casacpp.pc

about:
  home: https://casa.nrao.edu/
  license: LGPL-2.1-or-later
  license_file: casatasks/src/LICENSE.txt
  summary: "C++ libraries underlying CASA, the radio astronomical data processing package"

extra:
  recipe-maintainers:
    - pkgw
